// -------------------------------------------------------------
// 
// File Name: hdlsrc/mode_design/mode_design.v
// Created: 2021-04-29 15:51:22
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.1
// Target subsystem base rate: 0.1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// mode_out                      ce_out        0.1
// changing                      ce_out        0.1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mode_design
// Source Path: mode_design
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mode_design
          (clk,
           reset,
           clk_enable,
           mode_in,
           ce_out,
           mode_out,
           changing);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [1:0] mode_in;  // ufix2
  output  ce_out;
  output  [1:0] mode_out;  // ufix2
  output  changing;  // ufix1




  mode_selector_v2 u_mode_selector_v2 (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .mode_in(mode_in),  // ufix2
                                       .mode_out(mode_out),  // ufix2
                                       .changing(changing)  // ufix1
                                       );

  assign ce_out = clk_enable;

endmodule  // mode_design

