// -------------------------------------------------------------
// 
// File Name: hdlsrc/mode_design/mode_selector_v2.v
// Created: 2021-04-29 15:51:22
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: mode_selector_v2
// Source Path: mode_design/mode_selector_v2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module mode_selector_v2
          (clk,
           reset,
           enb,
           mode_in,
           mode_out,
           changing);

  // Default encoded enumeration values for type state_type_is_mode_selector_v2
  parameter state_type_is_mode_selector_v2_IN_Step1 = 2'd0, state_type_is_mode_selector_v2_IN_Step2 = 2'd1, state_type_is_mode_selector_v2_IN_WaitingChange = 2'd2, state_type_is_mode_selector_v2_IN_init = 2'd3;

  input   clk;
  input   reset;
  input   enb;
  input   [1:0] mode_in;  // ufix2
  output  [1:0] mode_out;  // ufix2
  output  changing;  // ufix1


  reg [1:0] is_mode_selector_v2;  // uint8
  reg [1:0] mode_buffer1;  // ufix2
  reg [1:0] mode_buffer2;  // ufix2
  reg [1:0] mode_out_reg;  // ufix2
  reg  changing_reg;  // ufix1
  reg [1:0] is_mode_selector_v2_next;  // enum type state_type_is_mode_selector_v2 (4 enums)
  reg [1:0] mode_buffer1_next;  // ufix2
  reg [1:0] mode_buffer2_next;  // ufix2
  reg [1:0] mode_out_reg_next;  // ufix2
  reg  changing_reg_next;  // ufix1


  always @(posedge clk or posedge reset)
    begin : mode_selector_v2_1_process
      if (reset == 1'b1) begin
        mode_buffer1 <= 2'b00;
        mode_buffer2 <= 2'b00;
        mode_out_reg <= 2'b00;
        changing_reg <= 1'b0;
        is_mode_selector_v2 <= state_type_is_mode_selector_v2_IN_init;
      end
      else begin
        if (enb) begin
          is_mode_selector_v2 <= is_mode_selector_v2_next;
          mode_buffer1 <= mode_buffer1_next;
          mode_buffer2 <= mode_buffer2_next;
          mode_out_reg <= mode_out_reg_next;
          changing_reg <= changing_reg_next;
        end
      end
    end

  always @(changing_reg, is_mode_selector_v2, mode_buffer1, mode_buffer2, mode_in,
       mode_out_reg) begin
    mode_out_reg_next = mode_out_reg;
    changing_reg_next = changing_reg;
    is_mode_selector_v2_next = is_mode_selector_v2;
    mode_buffer1_next = mode_buffer1;
    mode_buffer2_next = mode_buffer2;
    case ( is_mode_selector_v2)
      state_type_is_mode_selector_v2_IN_Step1 :
        begin
          if (mode_in != mode_buffer1) begin
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_Step1;
            mode_buffer1_next = mode_in;
          end
          else begin
            mode_buffer2_next = mode_in;
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_Step2;
          end
        end
      state_type_is_mode_selector_v2_IN_Step2 :
        begin
          if (mode_in != mode_buffer2) begin
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_Step1;
            mode_buffer1_next = mode_in;
          end
          else begin
            mode_out_reg_next = mode_buffer2;
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_WaitingChange;
          end
        end
      state_type_is_mode_selector_v2_IN_WaitingChange :
        begin
          if (mode_in == mode_out_reg) begin
            changing_reg_next = 1'b0;
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_WaitingChange;
          end
          else begin
            changing_reg_next = 1'b1;
            is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_Step1;
            mode_buffer1_next = mode_in;
          end
        end
      default :
        begin
          //case IN_init:
          mode_out_reg_next = 2'b00;
          changing_reg_next = 1'b1;
          is_mode_selector_v2_next = state_type_is_mode_selector_v2_IN_WaitingChange;
        end
    endcase
  end

  assign mode_out = mode_out_reg_next;
  assign changing = changing_reg_next;



endmodule  // mode_selector_v2

