// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Aug 31 17:28:31 2026

driver_ADS8691 driver_ADS8691_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.restart(restart_sig) ,	// input  restart_sig
	.driver_ncs(driver_ncs_sig) ,	// output  driver_ncs_sig
	.driver_sclk(driver_sclk_sig) ,	// output  driver_sclk_sig
	.driver_mosi(driver_mosi_sig) 	// output  driver_mosi_sig
);

