// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Thu Oct  1 09:24:21 2026

set_get_ads8691 set_get_ads8691_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.cmd_word(cmd_word_sig) ,	// input [31:0] cmd_word_sig
	.miso_1(miso_1_sig) ,	// input  miso_1_sig
	.miso_2(miso_2_sig) ,	// input  miso_2_sig
	.miso_3(miso_3_sig) ,	// input  miso_3_sig
	.miso_4(miso_4_sig) ,	// input  miso_4_sig
	.miso_5(miso_5_sig) ,	// input  miso_5_sig
	.miso_6(miso_6_sig) ,	// input  miso_6_sig
	.sclk(sclk_sig) ,	// output  sclk_sig
	.ncs(ncs_sig) ,	// output  ncs_sig
	.mosi(mosi_sig) ,	// output  mosi_sig
	.readed_half_words(readed_half_words_sig) ,	// output [95:0] readed_half_words_sig
	.set_get_done_out(set_get_done_out_sig) 	// output  set_get_done_out_sig
);

