// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Aug 31 17:44:32 2026

slaver_states slaver_states_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_hardware(rst_hardware_sig) ,	// input  rst_hardware_sig
	.rst(rst_sig) ,	// output  rst_sig
	.tx(tx_sig) ,	// output  tx_sig
	.convst_out(convst_out_sig) ,	// output  convst_out_sig
	.host_mosi_out(host_mosi_out_sig) ,	// output  host_mosi_out_sig
	.host_sclk_out(host_sclk_out_sig) ,	// output  host_sclk_out_sig
	.select0_0_out(select0_0_out_sig) ,	// output  select0_0_out_sig
	.select1_0_out(select1_0_out_sig) ,	// output  select1_0_out_sig
	.host_mode(host_mode_sig) ,	// output [1:0] host_mode_sig
	.reset_sm_laver_out(reset_sm_laver_out_sig) 	// output  reset_sm_laver_out_sig
);

