// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Fri Sep  4 08:58:34 2026

uart_tx_8 uart_tx_8_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.start(start_sig) ,	// input  start_sig
	.data_in(data_in_sig) ,	// input [7:0] data_in_sig
	.tx_out(tx_out_sig) ,	// output  tx_out_sig
	.busy_out(busy_out_sig) ,	// output  busy_out_sig
	.done_out(done_out_sig) 	// output  done_out_sig
);

