// -------------------------------------------------------------
// 
// File Name: hdlsrc/acquisition_store_crc_design/acquisition_store_crc_v2.v
// Created: 2021-05-05 20:32:04
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: acquisition_store_crc_v2
// Source Path: acquisition_store_crc_design/acquisition_store_crc_v2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module acquisition_store_crc_v2
          (clk,
           reset,
           enb,
           store_crc,
           store_crc_ok,
           csn,
           wen,
           msb,
           data_bus_out,
           addr_inc_write);

  // Default encoded enumeration values for type state_type_is_write_msb
  parameter state_type_is_write_msb_IN_NO_ACTIVE_CHILD = 2'd0, state_type_is_write_msb_IN_hold_write_msb = 2'd1, state_type_is_write_msb_IN_setup_write_msb = 2'd2, state_type_is_write_msb_b_IN_write_msb = 2'd3;
  // Default encoded enumeration values for type state_type_is_write_lsb
  parameter state_type_is_write_lsb_IN_NO_ACTIVE_CHILD = 2'd0, state_type_is_write_lsb_IN_hold_write_lsb = 2'd1, state_type_is_write_lsb_IN_setup_write_lsb = 2'd2, state_type_is_write_lsb_IN_write_lsb = 2'd3;
  // Default encoded enumeration values for type state_type_is_acquisition_store_crc_v2
  parameter state_type_is_acquisition_store_crc_v2_IN_wait_end = 2'd0, state_type_is_acquisition_store_crc_v2_IN_wait_store_crc = 2'd1, state_type_is_acquisition_store_crc_v2_state_type_is_acquisition_store_crc_v2_IN_write_lsb = 2'd2, state_type_is_acquisition_store_crc_v2_IN_write_msb = 2'd3;

  input   clk;
  input   reset;
  input   enb;
  input   store_crc;  // ufix1
  output  store_crc_ok;  // ufix1
  output  csn;  // ufix1
  output  wen;  // ufix1
  output  msb;  // ufix1
  output  data_bus_out;  // ufix1
  output  addr_inc_write;  // ufix1


  reg [1:0] is_acquisition_store_crc_v2;  // uint8
  reg [1:0] is_write_lsb;  // uint8
  reg [1:0] is_write_msb;  // uint8
  reg [1:0] wait_state_counter;  // ufix2
  reg  store_crc_ok_reg;  // ufix1
  reg  csn_reg;  // ufix1
  reg  wen_reg;  // ufix1
  reg  msb_reg;  // ufix1
  reg  data_bus_out_reg;  // ufix1
  reg  addr_inc_write_reg;  // ufix1
  reg [1:0] is_acquisition_store_crc_v2_next;  // enum type state_type_is_acquisition_store_crc_v2 (4 enums)
  reg [1:0] is_write_lsb_next;  // enum type state_type_is_write_lsb (4 enums)
  reg [1:0] is_write_msb_next;  // enum type state_type_is_write_msb (4 enums)
  reg [1:0] wait_state_counter_next;  // ufix2
  reg  store_crc_ok_reg_next;  // ufix1
  reg  csn_reg_next;  // ufix1
  reg  wen_reg_next;  // ufix1
  reg  msb_reg_next;  // ufix1
  reg  data_bus_out_reg_next;  // ufix1
  reg  addr_inc_write_reg_next;  // ufix1
  reg signed [3:0] sub_temp;  // sfix4
  reg [2:0] cast;  // ufix3
  reg signed [3:0] sub_temp_0;  // sfix4
  reg [2:0] cast_0;  // ufix3
  reg [2:0] t_0;  // ufix3
  reg signed [3:0] t_1;  // sfix4
  reg [2:0] t_2;  // ufix3
  reg signed [3:0] t_3;  // sfix4


  always @(posedge clk or posedge reset)
    begin : acquisition_store_crc_v2_1_process
      if (reset == 1'b1) begin
        is_write_lsb <= state_type_is_write_lsb_IN_NO_ACTIVE_CHILD;
        is_write_msb <= state_type_is_write_msb_IN_NO_ACTIVE_CHILD;
        wait_state_counter <= 2'b00;
        data_bus_out_reg <= 1'b0;
        is_acquisition_store_crc_v2 <= state_type_is_acquisition_store_crc_v2_IN_wait_store_crc;
        csn_reg <= 1'b1;
        wen_reg <= 1'b1;
        msb_reg <= 1'b0;
        store_crc_ok_reg <= 1'b0;
        addr_inc_write_reg <= 1'b0;
      end
      else begin
        if (enb) begin
          is_acquisition_store_crc_v2 <= is_acquisition_store_crc_v2_next;
          is_write_lsb <= is_write_lsb_next;
          is_write_msb <= is_write_msb_next;
          wait_state_counter <= wait_state_counter_next;
          store_crc_ok_reg <= store_crc_ok_reg_next;
          csn_reg <= csn_reg_next;
          wen_reg <= wen_reg_next;
          msb_reg <= msb_reg_next;
          data_bus_out_reg <= data_bus_out_reg_next;
          addr_inc_write_reg <= addr_inc_write_reg_next;
        end
      end
    end

  always @(addr_inc_write_reg, csn_reg, data_bus_out_reg, is_acquisition_store_crc_v2,
       is_write_lsb, is_write_msb, msb_reg, store_crc, store_crc_ok_reg,
       wait_state_counter, wen_reg) begin
    sub_temp = 4'sb0000;
    sub_temp_0 = 4'sb0000;
    t_0 = 3'b000;
    t_1 = 4'sb0000;
    t_2 = 3'b000;
    t_3 = 4'sb0000;
    cast = 3'b000;
    cast_0 = 3'b000;
    store_crc_ok_reg_next = store_crc_ok_reg;
    csn_reg_next = csn_reg;
    wen_reg_next = wen_reg;
    msb_reg_next = msb_reg;
    data_bus_out_reg_next = data_bus_out_reg;
    addr_inc_write_reg_next = addr_inc_write_reg;
    is_acquisition_store_crc_v2_next = is_acquisition_store_crc_v2;
    is_write_lsb_next = is_write_lsb;
    is_write_msb_next = is_write_msb;
    wait_state_counter_next = wait_state_counter;
    case ( is_acquisition_store_crc_v2)
      state_type_is_acquisition_store_crc_v2_IN_wait_end :
        begin
          if (store_crc == 1'b0) begin
            is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_IN_wait_store_crc;
            csn_reg_next = 1'b1;
            wen_reg_next = 1'b1;
            msb_reg_next = 1'b0;
            store_crc_ok_reg_next = 1'b0;
            addr_inc_write_reg_next = 1'b0;
          end
          else begin
            is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_IN_wait_end;
          end
        end
      state_type_is_acquisition_store_crc_v2_IN_wait_store_crc :
        begin
          if (store_crc == 1'b0) begin
            is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_IN_wait_store_crc;
            csn_reg_next = 1'b1;
            wen_reg_next = 1'b1;
            msb_reg_next = 1'b0;
            store_crc_ok_reg_next = 1'b0;
            addr_inc_write_reg_next = 1'b0;
          end
          else begin
            csn_reg_next = 1'b0;
            data_bus_out_reg_next = 1'b1;
            is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_state_type_is_acquisition_store_crc_v2_IN_write_lsb;
            is_write_lsb_next = state_type_is_write_lsb_IN_setup_write_lsb;
          end
        end
      state_type_is_acquisition_store_crc_v2_state_type_is_acquisition_store_crc_v2_IN_write_lsb :
        begin
          case ( is_write_lsb)
            state_type_is_write_lsb_IN_hold_write_lsb :
              begin
                msb_reg_next = 1'b1;
                addr_inc_write_reg_next = 1'b0;
                is_write_lsb_next = state_type_is_write_lsb_IN_NO_ACTIVE_CHILD;
                is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_IN_write_msb;
                is_write_msb_next = state_type_is_write_msb_IN_setup_write_msb;
              end
            state_type_is_write_lsb_IN_setup_write_lsb :
              begin
                wen_reg_next = 1'b0;
                wait_state_counter_next = 2'b11;
                is_write_lsb_next = state_type_is_write_lsb_IN_write_lsb;
              end
            default :
              begin
                //case IN_write_lsb:
                if (wait_state_counter != 2'b01) begin
                  t_0 = {1'b0, wait_state_counter};
                  t_1 = {1'b0, t_0};
                  sub_temp = t_1 - 4'sb0001;
                  if (sub_temp[3] == 1'b1) begin
                    cast = 3'b000;
                  end
                  else begin
                    cast = sub_temp[2:0];
                  end
                  if (cast[2] != 1'b0) begin
                    wait_state_counter_next = 2'b11;
                  end
                  else begin
                    wait_state_counter_next = cast[1:0];
                  end
                  is_write_lsb_next = state_type_is_write_lsb_IN_write_lsb;
                end
                else begin
                  wen_reg_next = 1'b1;
                  is_write_lsb_next = state_type_is_write_lsb_IN_hold_write_lsb;
                  addr_inc_write_reg_next = 1'b1;
                end
              end
          endcase
        end
      default :
        begin
          //case IN_write_msb:
          case ( is_write_msb)
            state_type_is_write_msb_IN_hold_write_msb :
              begin
                store_crc_ok_reg_next = 1'b1;
                csn_reg_next = 1'b1;
                data_bus_out_reg_next = 1'b0;
                addr_inc_write_reg_next = 1'b0;
                is_write_msb_next = state_type_is_write_msb_IN_NO_ACTIVE_CHILD;
                is_acquisition_store_crc_v2_next = state_type_is_acquisition_store_crc_v2_IN_wait_end;
              end
            state_type_is_write_msb_IN_setup_write_msb :
              begin
                wen_reg_next = 1'b0;
                wait_state_counter_next = 2'b11;
                is_write_msb_next = state_type_is_write_msb_b_IN_write_msb;
              end
            default :
              begin
                //case IN_write_msb:
                if (wait_state_counter != 2'b01) begin
                  t_2 = {1'b0, wait_state_counter};
                  t_3 = {1'b0, t_2};
                  sub_temp_0 = t_3 - 4'sb0001;
                  if (sub_temp_0[3] == 1'b1) begin
                    cast_0 = 3'b000;
                  end
                  else begin
                    cast_0 = sub_temp_0[2:0];
                  end
                  if (cast_0[2] != 1'b0) begin
                    wait_state_counter_next = 2'b11;
                  end
                  else begin
                    wait_state_counter_next = cast_0[1:0];
                  end
                  is_write_msb_next = state_type_is_write_msb_b_IN_write_msb;
                end
                else begin
                  wen_reg_next = 1'b1;
                  is_write_msb_next = state_type_is_write_msb_IN_hold_write_msb;
                  addr_inc_write_reg_next = 1'b1;
                end
              end
          endcase
        end
    endcase
  end

  assign store_crc_ok = store_crc_ok_reg_next;
  assign csn = csn_reg_next;
  assign wen = wen_reg_next;
  assign msb = msb_reg_next;
  assign data_bus_out = data_bus_out_reg_next;
  assign addr_inc_write = addr_inc_write_reg_next;



endmodule  // acquisition_store_crc_v2

