// -------------------------------------------------------------
// 
// File Name: hdlsrc/acquisition_store_crc_design/acquisition_store_crc_design.v
// Created: 2021-05-05 20:32:04
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.1
// Target subsystem base rate: 0.1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// store_crc_ok                  ce_out        0.1
// csn                           ce_out        0.1
// wen                           ce_out        0.1
// msb                           ce_out        0.1
// data_bus_out                  ce_out        0.1
// addr_inc_write                ce_out        0.1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: acquisition_store_crc_design
// Source Path: acquisition_store_crc_design
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module acquisition_store_crc_design
          (clk,
           reset,
           clk_enable,
           store_crc,
           ce_out,
           store_crc_ok,
           csn,
           wen,
           msb,
           data_bus_out,
           addr_inc_write);


  input   clk;
  input   reset;
  input   clk_enable;
  input   store_crc;  // ufix1
  output  ce_out;
  output  store_crc_ok;  // ufix1
  output  csn;  // ufix1
  output  wen;  // ufix1
  output  msb;  // ufix1
  output  data_bus_out;  // ufix1
  output  addr_inc_write;  // ufix1




  acquisition_store_crc_v2 u_acquisition_store_crc_v2 (.clk(clk),
                                                       .reset(reset),
                                                       .enb(clk_enable),
                                                       .store_crc(store_crc),  // ufix1
                                                       .store_crc_ok(store_crc_ok),  // ufix1
                                                       .csn(csn),  // ufix1
                                                       .wen(wen),  // ufix1
                                                       .msb(msb),  // ufix1
                                                       .data_bus_out(data_bus_out),  // ufix1
                                                       .addr_inc_write(addr_inc_write)  // ufix1
                                                       );

  assign ce_out = clk_enable;

endmodule  // acquisition_store_crc_design

